default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  user: postgres
  password: thanhdat97
  pool: 5

development:
  <<: *default
  database: redhat

test:
  <<: *default
  database: redhat_test

production:
  <<: *default
  database: redhat
